language: node_js

node_js:
  - '14'

script:
  - CI=false yarn install

# travis deployment
deploy:
  provider: heroku
  app: bonmunch
  api_key:
    secure: eyZ/1TwHx09Xn0c4m24o4TdZ0/E3ez8f1KKVAQC+VTH/Ha01Mkipertu6SXuHeYQcEbtbMj9L7krLOQobYIRDVWto1NX39pxYEiaEze4yhwX8TBEMwkB96D+BGobtPJua3mNajjm+wvrNOVIaWePJRXSM1yPvFUTpoXVX92e8ypCDw71w8KYbAyKR8lWkdhTNv0TLNfFcBAMAoe94AWlOmlPvcg4j6/WsyqpMMF2M461OgBzS8s7u3vKW4fydI7AADeOlweSoT0Fcz/vTdrqVwm3qVJxjWICFDrEXw04nNobBhLOJMXucwC/6mzwOM5+zEOKNCjD6YyFoweMcPvB7i0RU5M1opTmPk8qNwbsg1YAw5bdmwAV112NmKIOq8t/AQ2KO5S23RbEklFTMyAWDGKL9MsimWHMB6rzHJPy+zdPPuzyV1OeaEp+oEUuqcp5QRGdhDZQDFi+4eBLsn9xpC8G1nqzgeqopTkycxkNRrDmfGlghmmxNIny/dzNOb8Tjr4R5QH5DSl3HaMZABi1Edp5/QdAVUjIInrM0qAvlYux3IoDREFQ/bU7TYux4B/VsM4re4R92qLZKqdJrKjGOReKVSL5YF7XiR7koxI9GHwCEgd7LpPxfftIbNFMp+56ITJFoPwB4e0lxRWUns2gYcVkdWRTwaAf1rMjr0fWliU=
  on:
    repo: prithvi-varla/bon-munch
  skip_cleanup: true # This will skip removing the build at the end (but it is ok to remove this as we are not doing any build in travis, doing it in Heroku)